# Generated by Django 3.2 on 2021-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='price',
            new_name='phone_num',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='beg_time',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='client',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='done',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='order_list',
        ),
        migrations.AddField(
            model_name='courier',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='surname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
